### PR TITLE
Fixes more issues with python 27

### PR DESCRIPTION
**Pull request by ckcollab**
Resolves issue #25

# TODO

- [x] Write a few tests
- [x] Get passing on CircleCI
- [x] Get passing using Python 3
- [x] Conditional imports (Python 3 wont have future)
- [x] TRIED!! Add `super()` overrides to some `__init__` more simply
- [x] Fix str/unicode problem

### CODE REVIEW

**Comment by ckcollab** [comment]
Resolved #27 as well

**Comment by robrua** [comment]
Some of these changes will not run in 3.X. For example, unicode is not a type in 3.X.

I recall seeing the line "str = unicode" (if python2) somewhere in another project that was made backwards compatible. I feel like that's not a complete fix but could be a useful approach. Then again, I've never worked seriously w/python2 and certainly not w/backwards compatibility before.

**Comment by ckcollab** [comment]
Ahh, right, will do.

Also, would you like me to setup some automatic tests for this repo? To help me debug this stuff too? :D

**Comment by ckcollab** [comment]
If you would just enable http://circleci.com for this repo, I'll setup all the test configuration stuff and get tests passing for you :)

Or, if you don't mind, you could add me as a collaborator and I could do that stuff?

**Comment by robrua** [comment]
Hey - A good test suite would definitely be useful. I've got a set of terrible sanity checks that I run locally, which I can send you if you'd like. If you're willing to write some better tests too that'd be awesome.

I'm a little skeptical to add CI for this, as I don't really see a big benefit over locally running tests on a project this size/scope. The tests will probably require an API key, which could get messy w/CI.

As far as collaborators, I'd prefer to not add any who I don't know personally + share my plans/"vision" for the project. Feel free to email me if you want to talk about that more.

**Comment by ckcollab** [comment]
CI would be useful so, for example, on this PR you wouldn't have to run the tests yourself--you could just see that tests have passed. Especially useful for working with other people where there are many revisions/PRs flying around.

Tests won't actually hit any APIs as the responses will be mocked. We won't be testing Riot servers, just our code.

And yeah I can understand not allowing every person to collab, that's cool :) If you could enable http://circleci.com for this repo I'd love to setup the tests/everything for ya. That way ever subsequent PR will be tested. Could even add linting and other niceties! I love doing that stuff.

Anything I can do to help!

**Comment by jjmaldonis** [comment]
I'm going to throw out another idea here because I don't know much about circleci or how its pricing works.

Python has a builtin `unittest` module that is pretty easy to use as well. I doubt it's as versatile as circleci, but it also might be useful to have the test code directly in the repo, in addition to an `examples` directory (which we still need to make and add). I imagine being able to run something like `python run_tests.py`, in a python2 environment and in a python3 environment, and just having command line outputs say whether or not they passed. That's probably a bit more work than circleci because you have to navigate to the pull request and check both environments, but it's another option. Also, I think that because cassiopeia is so tightly integrated with the Riot API that it actually makes sense to make calls to it within the tests (or at least for some tests). For example, if Riot changes their data slightly then we will catch it right away.

We definitely need some tests and examples however we do things though, and if you are willing to help that would be **awesome**!

**Comment by robrua** [comment]
I'm definitely w/Jason on this one - the vast majority of bugs end up getting exposed by small differences in the Riot API data, be they changes Riot makes or a game missing some data or something. Testing w/mocked data wouldn't cover the bulk of errors, imo.

**Comment by ckcollab** [comment]
Yeah the plan is, basically, to use `unittest` (I prefer `py.test` though) and have CircleCI run those tests--it's free. All CircleCI will do is run the tests and let you know whether they passed or not. You'll definitely be able to run the unit tests, linter, and integration tests locally :)

And sure, we could do integration testing by pinging Riot servers, would just need to setup an environment variable on CircleCI with the keys and that's what the tests will use. If the same env var exists locally then we could run real integration tests testing everything. Does that all make sense?

**Comment by ckcollab** [comment]
BTW, I am setting this up on my fork -- I'll show you guys :D

 > I've got a set of terrible sanity checks that I run locally, which I can send you if you'd like.

Would love to get my hands on that!

**Comment by robrua** [comment]
To be entirely straightforward, I'm truly just not interested in having CI on cass at this point. It's extra overhead that I have to keep on top of, and I don't feel like the automation is particularly useful on a project like this (plus someone's dev key is going to have a lot of problems when tests are running). A better local test suite seems like a great thing to have, though.

How would you prefer I send you the existing tests?

**Comment by ckcollab** [comment]
A gist or something would be cool.

For my information, how is CI extra overhead, on top of having local tests? Assuming you always want to keep local tests running, isn't it less overhead because tests will already be run for you? In any case, I'll keep it up-to-date on my branch, and as long as I'm using it I'll make sure tests are passing.

**Comment by robrua** [comment]
It's another thing I have to stay on top of. I'd have to make sure I'm happy w/the quality of what's being run and make sure it's up-to-date. If you were to stop actively contributing to this project I'd also have to take over managing it.

It's not a huge hassle, but I just don't see any value in automating the tests right now; they very rarely even need to be run on pull requests, and I'm going to be testing locally anyway on any significant changes. I don't want to bring in tools that I don't feel like bring value.

**Comment by ckcollab** [comment]
Cool, thanks for the explanation :+1:

**Comment by robrua** [comment]
No problem - not trying to be stubborn, I just honestly feel like it's a lot more trouble than it's worth for you to set up, and just another straw on the camel's back from my perspective.

I'll send along what testing stuff I have later tonight.

**Comment by ckcollab** [comment]
I getchya :) 

Will hopefully have the branch task list completed for Python 2 + 3 and *some* tests by tomorrow night.

**Comment by ckcollab** [comment]
You can see circle in action [here](https://circleci.com/gh/ckcollab/cassiopeia), if you're curious!

Got one test to check Python 2 vs 3, seems to be working.

**Comment by ckcollab** [comment]
Did I merge in an old version of master or something? Lots of extra stuff in the PR...

**Comment by robrua** [comment]
Yeah, it looks like you merged into an old version and reverted some fixes :(

I put the shitty tests I have @ http://robrua.com/download/ for now instead of a gist.

**Comment by ckcollab** [comment]
What a dummy -.- think I fixed all the problems

**Comment by ckcollab** [comment]
Oh wow those tests look useful, I wonder if I could just actually run those? Only glanced at them still looking.

**Comment by ckcollab** [comment]
After looking through those tests a bit more I'm kind of confused, basically it's just making sure there are no exceptions?

Maybe we should consider a lot of the test stuff (unittest vs py.test, etc.) in another PR? I think a lot of people want at least Python2 working soon. I added one test for python 2 vs 3 and got both versions passing, still need to setup some more tests though.

**Comment by jjmaldonis** [comment]
Personally I don't think that a PR for support for Python2 is useful without tests. There _will_ be a significant amount of bugs. In addition, what version of Python2 are you using / planning to support here? 2.7? 2.6? Python 2.7 is a special version of Python2 written with features of Python3 backported -- so it was created after Python3. Python 2.6 does not support a noticeable number of features of Python 2.7, for example dictionary comprehensions. There are dictionary comprehensions in this code, and Rob made a design decision at the outset to use them rather than the uglier / less clear `dict(list-of-2-tuples)` syntax.

I also am curious why you use Python2. Is this more so habit, or because you have a significant amount of code written that deals with the Riot API in Python2, or something else? I personally use Python2 at work, but this is because I don't have admin rights over the clusters to install Python3 everywhere I would need it. That said, I still prefer Python3 whenever possible. It is just all around better. I haven't had a problem using both either, due to the awesomeness of virtual environments.

I just have this bad feeling that Python2 support is going to come at the cost of significant work and code quality, so I am a little worried about it overall. The question is whether that quality, readability, and worry about support for both versions is worth supporting Python2. As someone who uses both, I far prefer Python3. However, if there is a good case for using Python2 over Python3, I would still be open to that.

**Comment by ckcollab** [comment]
Why I use Python2.7: you guessed it, most of my code is in it and it "just works." I definitely do need to make the switch to Python 3! Just haven't yet. And support for Python2.7 alone is great. Adding support for earlier versions should be possible as well. Thanks to the awesome Python community, many of these problems are easily solved using existing modules.

As for muddying up the code base: for sure, as code gets more robust it naturally gets a little fuglier. Handling this edge case there, supporting another thing here, etc. But, when you cut out Python2 folks you are cutting out a huge portion of developers. I saw 2-3 people asking in the issues for this for Python2 support so that probably means 2-5x as many developers saw this lib and turned away.

What amount of test coverage would be ideal? Do we need integration tests, unit tests, etc.? I'll definitely be adding tests but I'm working on quite a few things and contributing to quite a few projects, might take a little time.

Currently there aren't any tests, so how is this much worse than the current state? I definitely agree tests are important... but if they are really important than CircleCi and its ilk (discussion from earlier) are also important! :)

It's pretty simple to run every test in every version of Python we'd like, unit tests would cover that well.

**Comment by robrua** [comment]
@ckcollab How can I contact you directly? I'd like to chat & get on the same page about these things.

**Comment by ckcollab** [comment]
eric@ckcollab.com should be fine, maybe skype if that's more useful?

**Pull request merged**
