### PR TITLE
Add python 27 support

### PR DESCRIPTION
**Pull request by ckcollab**
Resolves issue #17 and #18 I believe!

### CODE REVIEW

**Comment by robrua** [comment]
Hey - didn't know you could just drop that in and everything'll work on 2.7.

It'd be great if the 2.7 dependencies were only getting pulled in/installed for 2.7 users and not 3.X.

**Comment by ckcollab** [comment]
Yeah that's a good point, not sure how to do that? Is that possible with pypi/pip?

**Comment by robrua** [comment]
I've never tried it, but you can get the current version w/ sys.version_info

install_requires could be set conditionally on that, and I don't see why it wouldn't work

**Comment by ckcollab** [comment]
I just tested that, seemed to work! Thanks for the quick responses :D

**Comment by robrua** [comment]
Looks good, thanks for the effort.

**Pull request merged**
